# Generated by Django 6.0.5 on 2026-09-09 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('approve_leave', 'Can approve leave')]},
        ),
    ]
