# Generated by Django 6.0.5 on 2026-08-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_outlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
